### ISSUE TITLE
[3|Resource Page (Item) and Note Taking Feature] The Hamburger Menu

### ISSUE THREAD

**Issue by vo-d** [Builder-s-League/BuildersLeague-Edition1#12]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 15 points |
| Difficulty rating | ★★★☆☆ | 
| Maximum Assignees | 3 person | 

</div>

🤔 Problem Statement
------------------------------------------
![Screenshot 2024-09-21 162658](https://github.com/user-attachments/assets/7308fcf0-566a-4c9c-8ddc-258595fcf9bc)

Create a sidebar that can be opened when the user clicks the hamburger menu on the top left of the Resource Page.

The sidebar will have a blank background, populated with the list of topics fetched from the Payload CMS along with the user progress for each of the topics fetched from Supabase. The user progress for each topic will be the percentage between the number of resources that the user has read over the total number of resources in a topic.

The first item on the sidebar should help the user to go back to the topic detail page that the current resource belongs to.

If the user clicks on the 'x' button on the top left, the sidebar will close. If the user hover outside of the sidebar, the sidebar will also close.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, some integration tests for Payload CMS and Supabase.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- Payload CMS
- NextJS
- Supabase/PostGresQL

**Comment by thejasveer** [comment]
@vo-d @hzz4343 @Iwaslazkis Can you assign this to me

**Comment by khnatiuk** [comment]
@thejasveer I like your enthusiasm! This feature remains locked for now but once it opens up we can start assignments.

**Comment by ViniOkamoto** [comment]
Could assign me as well? @al-Sajjadieh or @hzz4343

**Comment by ash0359** [comment]
i want to work on this

**Comment by MandeepPaul** [comment]
I want to work on this!!

**Comment by Iwaslazkis** [comment]
Hey @ViniOkamoto! Apologies for the mix up, I didn't see the Pull Request call! I spoke to Mandeep and Ash yesterday, and have since removed them from the issue.
