### ISSUE TITLE
⭐ Base DB Schema

### ISSUE THREAD

**Issue by Iwaslazkis** [Builder-s-League/BuildersLeague-Edition1#127]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 30 points |
| Difficulty rating | ★★★★★| 
| Maximum Assignees | 6 person | 

</div>

🤔 Problem Statement
------------------------------------------
As we move more into backend features, builders will suggest new DB changes as migrations. This can be done by making tables in the [Supabase dashboard](https://www.youtube.com/watch?v=6fFHgHqSbt8) and then using Supabase migrations, as shown here: https://www.youtube.com/watch?v=Kx5nHBmIxyQ

The problem is that making schemas that are redundant is hard! So, if you want to take a crack at your data modeling skills, this piece involves looking through the entire project pieces, and modeling a schema that looks over the entire set of features. Refer to these sketches ([CBH](https://excalidraw.com/#json=WRNmT8B5qn43S8yf5onBw,7wvbggLXn4hy56_xlwgHFw), [HR](https://excalidraw.com/#json=-eCYiuebHl139nNQZdF95,yxEfmb-gKAENHVJVvpG_zA), [End-user]( https://excalidraw.com/#json=pf-JPwxJjE6G-2HAuoczX,x5pNjJ4HKuQIeiSB20QWTA)) and the existing issues for more info.

As part of this, make sure to also create a seeding file (refer to the video on migrations above for more info).

🧪 Required Tests
-------------------------------------
None!

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- NextJS
- Supabase/PostGresQL

**Comment by Tyson-a** [comment]
can I be assigned to this one?

**Comment by shop2008** [comment]
I would like to work on this

**Comment by ViniOkamoto** [comment]
I would like to work on this as well ^^

**Comment by Sneezy-w** [comment]
I want to work on this

**Comment by thejasveer** [comment]
can i be assigned to this @al-Sajjadieh

**Comment by smtoyedeji** [comment]
Can I be assigned to this?

**Comment by PJ-Bernal** [comment]
I want to jump in here
