### ISSUE TITLE
[5|Resource Page (Item) and Note Taking Feature] The tooltip

### ISSUE THREAD

**Issue by vo-d** [Builder-s-League/BuildersLeague-Edition1#14]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 10 points |
| Difficulty rating | ★★☆☆☆ | 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
![Screenshot 2024-09-21 151554](https://github.com/user-attachments/assets/2ccbacfd-a132-4b86-9549-b4dfd24673ce)

Create a tooltip and make it appear every time the user selects a piece of text in the resource article's content. The Highlight and Make a Note buttons will do nothing for now. The copy button will do a copy action. 

You can either use an external library or develop your own logic for this tooltip.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS

**Comment by thejasveer** [comment]
can you assign me this feature @vo-d  @hzz4343  @Iwaslazkis

**Comment by thejasveer** [comment]
can you assign me this feature @hzz4343

**Comment by ViniOkamoto** [comment]
Working on this one!

**Comment by khnatiuk** [comment]
@thejasveer message me once you're done the Reporting feature and I'll get you added to these.

**Comment by thejasveer** [comment]
@khnatiuk  yeah i am free now!
