### ISSUE TITLE
[6|Resource Page (Item) and Note Taking Feature] The Note-making Box and the Comment Section

### ISSUE THREAD

**Issue by vo-d** [Builder-s-League/BuildersLeague-Edition1#15]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 20 points |
| Difficulty rating | ★★★★☆ | 
| Maximum Assignees | 4 person | 

</div>

🤔 Problem Statement
------------------------------------------
| Note-making Box| Comment Section|
|:-------|:------:|
| ![Screenshot 2024-09-21 152810](https://github.com/user-attachments/assets/b9e6626e-1a20-44b7-b22d-a01027d89858) | ![Screenshot 2024-09-21 170256](https://github.com/user-attachments/assets/981b94a3-1ae2-4999-9da3-b9a21654fd55) |

You can see that there"s a tooltip appears when you select a piece of text in the resource article. However, the Highlight and Make a note buttons do nothing. 

Develop a feature that when the user clicks make a note, the take note box like in the image above appears. If the user enters text and clicks save to my note, the note will be saved privately and only that user can read the note. If the user clicks post to public, the note will be saved publicly and everyone can read the note. If the user checks the box hide my name and click post to public, the note will be saved publicly but your username is not shown in the note. The user can not hide his/her name when saving the note privately.

The Highlight button in the tooltip will save an empty note privately.

Every time the user loads the resource page, all the private notes will be loaded. Every section of the text that have the private note will be highlighted. (light yellow or light blue).

Use Supabase to store notes.

The comment section uses similar logic to taking notes. But instead of making a note for a piece of text in the resource content, it makes a note for the entire content. The content will not be highlighted as a result of the comments. 

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, some integration tests for Supabase.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- Payload CMS
- NextJS
- Supabase/PostGresQL

**Comment by thejasveer** [comment]
Can i work on this @hzz4343  @vo-d  @Iwaslazkis

**Comment by khnatiuk** [comment]
@thejasveer message me once you're done the reporting feature and we'll get you added!

**Comment by thejasveer** [comment]
@khnatiuk i am free now!

**Comment by khnatiuk** [comment]
@thejasveer you're in!

**Comment by calmHeaven** [comment]
@khnatiuk Could you assign me this one

**Comment by khnatiuk** [comment]
@calmHeaven you're in!

**Comment by Ryan-L3** [comment]
Completed the merge and assigned points
