### ISSUE TITLE
[1|End-user Navbar] Breadboard

### ISSUE THREAD

**Issue by Iwaslazkis** [Builder-s-League/BuildersLeague-Edition1#2]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 3 points |
| Difficulty rating | ★★☆☆☆ | 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
Make a breadboard for each screen in the fat-marker sketch. Every place and affordance should be accounted for, but don't focus on making it look pretty. This should be essentially a bare HTML file, with no JS, and only CSS if required for basic layouts. Implement fake navigation and interactions using normal `<a>` tags. This purely for getting an interactive "skeleton" up, and seeing in real life whether this design would work, or has any major problems.
Please see [this page](https://basecamp.com/shapeup/3.2-chapter-11#integrate-one-slice) for more info on what your breadboard should be like (and, if you want understand the fat-marker sketch and places affordances drawing better, please see [this page](https://basecamp.com/shapeup/1.3-chapter-04)).

🧪 Required Tests
-------------------------------------
_None (but the Code Wizard will review whether or not your code warrants some tests! Review the [Code & Testing Guidelines](https://google.com) for more info)_

⚠️ Careful about:
-------------------
- Don't make a separate desktop design. There should be one design, that works both in landscape and portrait orientations.

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn

**Comment by NicoleOkamoto** [comment]
I want to work on this feature @puma

**Comment by ViniOkamoto** [comment]
I want to work on this feature @puma

**Comment by khnatiuk** [comment]
@NicoleOkamoto it's yours! You are now assigned.

**Comment by khnatiuk** [comment]
@ViniOkamoto it's yours!

**Comment by LeopoldXing** [comment]
https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/103

**Comment by LeopoldXing** [comment]
https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/103
