### ISSUE TITLE
[FEAT] CBH - Organization Dashboard and Management Page

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#32]
| 🎨 Fat-marker Sketch | 🧑‍🏫 Places and Affordances |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/0d83674c-ea47-4601-9c22-14b64b40943f) | ![image](https://github.com/user-attachments/assets/1177d934-a679-4122-918f-864f72e39f41)|

_Not sure what a fat-marker sketch and places & affordances drawing is? Please see [this page](https://basecamp.com/shapeup/1.3-chapter-04) for more info!_

<p>
This is the Organization Dashboard and Management Page, where CBH (Community of Big Hearts), the owner of application, is able to manage their customers. 

The organization dashboard shows the list of organizations (both active and inactive ones), where CBH can access and edit organization information and employees in the organization. 

This page can only be viewed by users who logged in as CBH.
</p>

------------------------------------------

🤔 What problems does this solve?
------------------------------------------
- Help CBH manages customers.

🤖 Technologies focused on in this feature
------------------------------------------
- React
- Tailwind
- Shadcn
- Some PayloadCMS
- Some NextJS
- Some Supabase/PostGreSQL

🍕 Related Pieces
-------------------------------------
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37

**Comment by Sneezy-w** [comment]
I want to work on this

**Comment by mariannalf** [comment]
I will be working on the [BUG] styling fix for this feature @puma
