### ISSUE TITLE
[1|CBH - Organization Management Page] Breadboard

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#33]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 3 points |
| Difficulty rating | ★★☆☆☆ | 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
Make a breadboard for each screen in the fat-marker sketch. Every place and affordance should be accounted for, but don't focus on making it look pretty. This should be essentially a bare HTML file, with no JS, and only CSS if required for basic layouts. Implement fake navigation and interactions using normal `<a>` tags. This purely for getting an interactive "skeleton" up, and seeing in real life whether this design would work, or has any major problems.
Please see [this page](https://basecamp.com/shapeup/3.2-chapter-11#integrate-one-slice) for more info on what your breadboard should be like (and, if you want understand the fat-marker sketch and places affordances drawing better, please see [this page](https://basecamp.com/shapeup/1.3-chapter-04)).

- Make it so that only the user who logged in as CBH can see and stay on this site. The rest will be redirected to home.

🧪 Required Tests
-------------------------------------
_None (but the Code Wizard will review whether or not your code warrants some tests! Review the [Code & Testing Guidelines](https://google.com) for more info)_

⚠️ Careful about:
-------------------
- Don't make a separate desktop design. There should be one design, that works both in landscape and portrait orientations.

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn

**Comment by NadiiaTysh** [comment]
I want this

**Comment by khnatiuk** [comment]
@NadiiaTysh you're in!

**Comment by Eugenia821** [comment]
Add me please here too @khnatiuk

**Comment by khnatiuk** [comment]
@Eugenia821 you're in!

**Comment by Eugenia821** [comment]
I've done something based on @NadiiaTysh code:

1. Login check: I've added a check using the useEffect hook to redirect any user that isn't logged in as "CBH".


2. Responsive layout: Tailwind's flex, md:flex-row, and gap-2 utilities create a flexible and responsive design that adjusts between portrait and landscape orientations.


3. Basic navigation: I used <a> tags for fake interactions and navigation, as required by the task.


4. Styling: Basic Tailwind styling has been applied to give a skeleton look while maintaining readability and ease of interaction

Code to test on Saturday morning:

import React, { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function OrgDashboard() {
  const router = useRouter();
  const currentUser = 'CBH'; // Replace with dynamic user logic as needed

  // Redirect non-CBH users to home
  useEffect(() => {
    if (currentUser !== 'CBH') {
      router.push('/'); // Redirect to home if user is not CBH
    }
  }, [currentUser, router]);

  return (
    <div className='container mx-auto p-4'>
      {/* Search Bar and Add/Export buttons */}
      <div className='flex flex-col md:flex-row md:justify-between mb-6'>
        <input
          className='border p-2 mb-2 md:mb-0'
          placeholder='Search organization...'
        />
        <div className='flex gap-2'>
          <a href='#' className='bg-blue-500 text-white p-2 rounded'>Add</a>
          <a href='#' className='bg-blue-500 text-white p-2 rounded'>Export</a>
        </div>
      </div>

      {/* Organizations List */}
      {['Org 1', 'Org 2', 'Org 3'].map((org, idx) => (
        <div key={idx} className='flex flex-col md:flex-row justify-between items-center p-4 mb-4 border rounded'>
          <div className='text-lg'>{org}</div>
          <div className='flex gap-2'>
            <a href='#' className='bg-green-500 text-white p-2 rounded'>Edit Org</a>
            <a href='#' className='bg-yellow-500 text-white p-2 rounded'>Edit Members</a>
          </div>
        </div>
      ))}

      {/* Bottom Navigation */}
      <div className='flex justify-around mt-6'>
        <a href='#' className='bg-gray-500 text-white p-2 rounded'>OM</a>
        <a href='#' className='bg-gray-500 text-white p-2 rounded'>OGC</a>
        <a href='#' className='bg-gray-500 text-white p-2 rounded'>C</a>
        <a href='#' className='bg-gray-500 text-white p-2 rounded'>FB</a>
        <a href='#' className='bg-gray-500 text-white p-2 rounded'>S</a>
      </div>
    </div>
  );
}

**Comment by NadiiaTysh** [comment]
@khnatiuk we need help with PR please 😊

**Comment by khnatiuk** [comment]
@NadiiaTysh I'm sending a code wizard your way. :)

**Comment by khnatiuk** [comment]
@Builder-s-League/code-wizard can you verify and close this?

**Comment by khnatiuk** [comment]
This

**Comment by khnatiuk** [comment]
MR: [121](https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/121).
