### ISSUE TITLE
[2|CBH - Organization Management Page] Add new organization

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#34]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 15 points |
| Difficulty rating | ★★★☆☆ | 
| Maximum Assignees | 3 person | 

</div>

🤔 Problem Statement
------------------------------------------
![image](https://github.com/user-attachments/assets/46f2b87a-4b93-4e8f-b0a6-62881c020d33)

Create the feature of adding new organizations. The input information is:
- organization name, address, contact information
- organization HR name
- organization HR email
- "submit" button

🧪 Required Tests
-------------------------------------
Mainly screenshot tests.
Review the [Code & Testing Guidelines](https://google.com/) for more info.

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS
- Supabase/PostGresQL

**Comment by hzz4343** [comment]
@project manager, please assign me this piece.

**Comment by hzz4343** [comment]
@project manager, I need a helper

**Comment by hzz4343** [comment]
@project manager, I would like to help.

**Comment by Eugenia821** [comment]
Can I get this task please @https://github.com/khnatiuk

**Comment by NadiiaTysh** [comment]
Can I have this task please? Kevin

**Comment by al-Sajjadieh** [comment]
Hi, You can use https://ui.shadcn.com/examples/dashboard for better UI !

**Comment by Ryan-L3** [comment]
@khnatiuk @NadiiaTysh @Eugenia821 
I have merged the pull request and assigned the points.

**Comment by mariannalf** [comment]
I will be working on the [BUG] styling fix for this feature @puma
