### ISSUE TITLE
[3|CBH - Organization Management Page] Edit organization

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#35]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 15 points |
| Difficulty rating | ★★★☆☆ | 
| Maximum Assignees | 3 person | 

</div>

🤔 Problem Statement
------------------------------------------
![image](https://github.com/user-attachments/assets/08082a00-9470-46f5-bbd6-c08c28c1c9f1)

Create the feature of editing existing organizations, where CBH is able to change organization's information, delete org, enable/disable org, reset password of HR.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests.
Review the [Code & Testing Guidelines](https://google.com/) for more info.

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS
- Supabase/PostGresQL

**Comment by Sneezy-w** [comment]
I want work on this

**Comment by shop2008** [comment]
I would like to work on this

**Comment by DemonicQuasar** [comment]
@project manager, I'd like to work on this
