### ISSUE TITLE
[4|CBH - Organization Management Page] Search bar

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#36]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 10 points |
| Difficulty rating | ★★☆☆☆ | 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
![image](https://github.com/user-attachments/assets/bf644084-f9a5-4fd1-a117-7a143b9dd8c3)

Realize the search bar feature.

Create a filter (active/inactive).

🧪 Required Tests
-------------------------------------
Mainly screenshot tests.
Review the [Code & Testing Guidelines](https://google.com/) for more info.

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS
- Supabase/PostGresQL

**Comment by Sneezy-w** [comment]
I am working on this

**Comment by Ryan-L3** [comment]
@khnatiuk @Sneezy-w Related to PR: https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/184
I have merged and assigned points.
