### ISSUE TITLE
[5|CBH - Organization Management Page] Export organization list

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#37]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 10 points |
| Difficulty rating | ★★☆☆☆ | 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
![image](https://github.com/user-attachments/assets/8a8f237b-4496-4f4a-a37e-a7d2086e36b1)

Export organization list to a CSV file. After clicking the "export" button, it generates a csv file for download.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests.
Review the [Code & Testing Guidelines](https://google.com/) for more info.

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS
- Supabase/PostGresQL

**Comment by Sneezy-w** [comment]
I am working on this

**Comment by Ryan-L3** [comment]
@khnatiuk @Sneezy-w 
I have completed the merge and assigned the points
