### ISSUE TITLE
[1|Topic Detail Page] Breadboard

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#4]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 3 points |
| Difficulty rating | ★★☆☆☆ | 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
Make a breadboard for each screen in the fat-marker sketch. Every place and affordance should be accounted for, but don't focus on making it look pretty. This should be essentially a bare HTML file, with no JS, and only CSS if required for basic layouts. Implement fake navigation and interactions using normal `<a>` tags. This purely for getting an interactive "skeleton" up, and seeing in real life whether this design would work, or has any major problems.
Please see [this page](https://basecamp.com/shapeup/3.2-chapter-11#integrate-one-slice) for more info on what your breadboard should be like (and, if you want understand the fat-marker sketch and places affordances drawing better, please see [this page](https://basecamp.com/shapeup/1.3-chapter-04)).

🧪 Required Tests
-------------------------------------
_None (but the Code Wizard will review whether or not your code warrants some tests! Review the [Code & Testing Guidelines](https://google.com) for more info)_

⚠️ Careful about:
-------------------
- Don't make a separate desktop design. There should be one design, that works both in landscape and portrait orientations.

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn

**Comment by Sahib4** [comment]
I can work on this one @puma

**Comment by khnatiuk** [comment]
@Sahib4 it's yours! You're now assigned.

**Comment by namanparashar123** [comment]
I can work on this as well @puma

**Comment by Iwaslazkis** [comment]
@khnatiuk I added in @namanparashar123 , but he is talking with @Sahib4 right now.

**Comment by khnatiuk** [comment]
@namanparashar123 @Sahib4 can you come see me? There are folks ready to work on Phase 2 but we're unsure whether you have completed Phase 1 yet.

**Comment by khnatiuk** [comment]
@ViniOkamoto please let a PuMA know if you want to be added to this issue.

**Comment by ViniOkamoto** [comment]
On it already! @khnatiuk

**Comment by NicoleOkamoto** [comment]
Please add me to it @puma

**Comment by khnatiuk** [comment]
Yay!
