### ISSUE TITLE
[2|Topic Detail Page] A list of topic resources

### ISSUE THREAD

**Issue by Iwaslazkis** [Builder-s-League/BuildersLeague-Edition1#5]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 20 points |
| Difficulty rating | ★★★☆☆ | 
| Maximum Assignees | 4 person | 

</div>

🤔 Problem Statement
------------------------------------------
![Screenshot from 2024-09-17 20-09-27](https://github.com/user-attachments/assets/04e50ac0-a858-4954-bcfe-6fbf77709692)

Create a list of items that make up the various resources of the topic that is displayed on the topic detail page. An example of a resource can be a video, a livestream, or an article. A resource can also have external links, or it can have internal links.

As the user clicks on each resource, once they view it, a flag will be set in the database that will indicate they viewed it (like a purple link on a Google Search result). If they have already viewed this resource, the row should somehow indicate its viewed; but doesn't have to be with the word "Done!". A checkmark is fine, for example, feel free to be creative here! There is no need to label it as "New" to start with.

Most resources will look the same inside this list, regardless of their type, but the livestream one is special: it should display a date and time of when the livestream will happen in the row somewhere (it doesn't have to look the same as the sketch), and when you click on it will leave the app and go to an external link. If the livestream is already concluded, instead of displaying the date and time, it should instead show a message saying "livestream over. Click for recording" or something along those lines; and when the user clicks on it, it will take them to the recording page.

The content that is linked on each item, regardless of if it is an external link or internal link, will be managed on Payload CMS. The team responsible for this feature should also make sure that the list fetches the row data from the CMS, and that the proper support for updating what is on the list is added into Payload CMS.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, some integrations tests for Payload CMS.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- Payload CMS
- NextJS
- Supabase/PostGresQL

**Comment by mariannalf** [comment]
I would like to work on this one @puma

**Comment by PJ-Bernal** [comment]
I want to build this!! @puma

**Comment by ViniOkamoto** [comment]
I want to build this one @puma

**Comment by NicoleOkamoto** [comment]
I would loke to work on this one @puma

**Comment by khnatiuk** [comment]
@mariannalf @PJ-Bernal @ViniOkamoto @NicoleOkamoto you are now assigned! May the code be with you...

**Comment by khnatiuk** [comment]
@ViniOkamoto Phase 1 never got completed and the assignees are unavailable. Would you like me to add you to [Issue 4](https://github.com/Builder-s-League/BuildersLeague-Edition1/issues/4) so you can complete it and receive the points?

**Comment by al-Sajjadieh** [comment]
Hi, You can use https://ui.shadcn.com/examples/dashboard for better UI !

**Comment by Ryan-L3** [comment]
@ViniOkamoto @NicoleOkamoto @PJ-Bernal @mariannalf @khnatiuk 
I've assigned points and merged the code.
*Please remember to remove the mock when database is implemented*
