### ISSUE TITLE
[2|About Page] About Page

### ISSUE THREAD

**Issue by vo-d** [Builder-s-League/BuildersLeague-Edition1#52]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 10 points |
| Difficulty rating | ★★☆☆☆ | 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
Create an About Page where end-users see the information about the app.

The About Page should include:
- A description of the app.
- A help button that will lead the user to the app tour page.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, some integrations tests for Payload CMS.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- Payload CMS
- NextJS
- Supabase/PostGresQL

🙋 Helpers
---------------------------
@Sneezy-w

**Comment by Simonwmm** [comment]
i can take this @puma

**Comment by shop2008** [comment]
I would like to work on this @Iwaslazkis

**Comment by PJ-Bernal** [comment]
I want to help here! @puma

**Comment by khnatiuk** [comment]
@Simonwmm @shop2008 you are now assigned!

**Comment by khnatiuk** [comment]
Hi @PJ-Bernal this issue is currently full but we can use your help on other issues!

**Comment by khnatiuk** [comment]
HELPER added: @Sneezy-w

**Comment by khnatiuk** [comment]
@vo-d what is Phase 2 supposed to achieve? Do the fields need to be editable or linked back to a Content Management System? I'm asking on behalf of @Simonwmm

**Comment by khnatiuk** [comment]
Hi @shop2008! I noticed you are working on the Database Issue so I'm going to take you off this issue for now so someone else can work on it. Please reach out if I removed you in error!

**Comment by khnatiuk** [comment]
@Sneezy-w are you working on any other issues right now or just this one: "[[2|About Page] About Page](https://github.com/Builder-s-League/BuildersLeague-Edition1/issues/52#top)
#52"

**Comment by Sneezy-w** [comment]
I am working on the DB Schema https://github.com/Builder-s-League/BuildersLeague-Edition1/issues/127

**Comment by shop2008** [comment]
@khnatiuk we're almost done with this, we will submit later

**Comment by shop2008** [comment]
@khnatiuk Hi, Kevin, this task is done, but it's still showing open, and we haven't our my points for it, can you help me check Thanks!

**Comment by Ryan-L3** [comment]
@khnatiuk @shop2008 @Simonwmm 
Sorry about that! I have assigned the points and will close the issue.
