### ISSUE TITLE
[2|CBH & HR - UGC & Banned words Dashboard] UGC tables

### ISSUE THREAD

**Issue by vo-d** [Builder-s-League/BuildersLeague-Edition1#55]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 25 points |
| Difficulty rating | ★★★★★| 
| Maximum Assignees | 6 person | 

</div>

🤔 Problem Statement
------------------------------------------
![Screenshot 2024-09-29 204421](https://github.com/user-attachments/assets/593f7ec1-a4f9-4920-b2b8-c706365ca78e)

Create a table to show the UGC list. The list will include users' public notes and shared articles. Add pagination to this table. The table will include these fields:
- A checkbox field that allows the user to perform action on more than one row at a time.
- Note (public notes/user thoughts on an article)
- Linked content (where the public note point to/link to the article that the user shared)
- Author (Note's author username)
- Organization (the organization to which the user belongs to)
- Approval & Report 

The list will contain UGC  from all organizations if the user is logged in as CBH. If the user is logged in as HR of a company, then only display the UGC from that organization.

If the user is logged in as CBH, for a new post or a post that has only been approved by HR, show the 'approve' button and the 'deny' button in the Approval & Report column. If the UGC is approved by CBH, then show the 'remove' button and a 'report' field to the CBH to remove the post or to see the report count.

 If the user is logged in as HR, for a new post or a post that has only been approved by CBH, also show the 'approve' button and the 'deny' button in the Approval & Report column.  If the UGC has been approved by HR, then show the 'remove' button and a 'report' field to HR to remove the post or to see the report count.

For your information: if CBH or HR approves, the post will be on the feed, but if another party denies it after that, the post will be taken down no matter what. (You don't have to do anything here. This is just an explanation of why we have separate approve and deny for CBH and HR)

For every cell in the table, if the content is more than how much a cell can show, when the user clicks on the cell, a pop-up will appear and show the rest of the content. 

When the user clicks on the 'Remove' button, a confirmation pop-up will appear. When the user clicks on the 'Deny' button, a pop-up will appear and prompt the user for a reason. 

The 'Export selected' button will export a CSV of all chosen Notes. The 'Delete selected' button will delete all of the chosen notes.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, and some integration tests for Supabase and Payload CMS.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- Payload CMS
- NextJS
- Supabase/PostGresQL
- AppFlowy

**Comment by PJ-Bernal** [comment]
Im gonna work on this. @puma

**Comment by Tyson-a** [comment]
Can I be assigned here @hzz4343

**Comment by khnatiuk** [comment]
Hey @PJ-Bernal! Please message me and let me know whether you were able to complete this issue and we will ensure you receive the assigned points. We're temporarily locking it to focus on the priority issues identified on this [Discord announcement](https://discord.com/channels/1255316387417821306/1255316387417821311/1292313588706447503).

**Comment by Ryan-L3** [comment]
@khnatiuk @PJ-Bernal @ringram58 
I have assigned points and merged the pull request. JSON appSmith file has been saved.
