### ISSUE TITLE
[2|CBH - Report Dashboard] Report Tables

### ISSUE THREAD

**Issue by vo-d** [Builder-s-League/BuildersLeague-Edition1#65]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 30 points |
| Difficulty rating | ★★★★☆| 
| Maximum Assignees | 5 person | 

</div>

🤔 Problem Statement
------------------------------------------
![Screenshot 2024-09-29 214703](https://github.com/user-attachments/assets/d2ac410f-44e7-4200-b0a9-d781d5da15fd)

Create a table to show the report list. Add pagination to this table. The table contains these fields:
- A checkbox field that allows the user to perform action on more than one row at a time.
- Note (public notes/user thoughts on an article) that is reported
- Link Content (Address of the reported note).
- Author (Note's author username) of the reported note.
- Report Content (List of reporters and reason they reported).
- Keep? (to keep or remove the UGC out of the Feed).

For every cell in the table, if the content is more than how much a cell can show, when the user clicks on the cell, a pop-up will appear and show the rest of the content. 

When the user clicks on the 'Remove' button, a confirmation pop-up will appear.

The 'Export selected' button will export a CSV of all chosen Notes. The 'Delete selected' button will delete all of the chosen notes.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, and some integration tests for Supabase and Payload CMS.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- Payload CMS
- NextJS
- Supabase/PostGresQL
- AppFlowy

**Comment by thejasveer** [comment]
I am working. on it

**Comment by calmHeaven** [comment]
@thejasveer and I are on it
