### ISSUE TITLE
[4|Topic Detail Page] Hamburger Menu button

### ISSUE THREAD

**Issue by vo-d** [Builder-s-League/BuildersLeague-Edition1#7]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 15 points |
| Difficulty rating | ★★★☆☆ | 
| Maximum Assignees | 3 person | 

</div>

🤔 Problem Statement
------------------------------------------
![Screenshot 2024-09-18 141453](https://github.com/user-attachments/assets/8763ff48-116e-41c4-965e-2ff33b42e33b)

Create a sidebar that can be opened when the user clicks the hamburger menu on the top left of the Topic Detail Page.

The sidebar will have a blank background, populated with the list of topics fetched from the Payload CMS along with the user progress for each of the topics fetched from Supabase. The user progress for each topic will be the percentage between the number of resources that the user has read over the total number of resources in a topic.

If the user clicks on the 'x' button on the top left, the sidebar will close. If the user hover outside of the sidebar, the sidebar will also close.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, and some integration tests for Payload CMS.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- Payload CMS
- NextJS
- Supabase/PostGresQL

**Comment by ViniOkamoto** [comment]
Can I work on this one? @hzz4343

**Comment by LeopoldXing** [comment]
https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/194

**Comment by LeopoldXing** [comment]
https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/194
