### ISSUE TITLE
[1|CBH - Survey Dashboard & Add Survey] Breadboard

### ISSUE THREAD

**Issue by vo-d** [Builder-s-League/BuildersLeague-Edition1#73]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 3 points |
| Difficulty rating | ★★☆☆☆ | 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
Make a breadboard for each screen in the fat-marker sketch. Every place and affordance should be accounted for, but don't focus on making it look pretty. This should be essentially a bare HTML file, with no JS, and only CSS if required for basic layouts. Implement fake navigation and interactions using normal `<a>` tags. This purely for getting an interactive "skeleton" up, and seeing in real life whether this design would work, or has any major problems.
Please see [this page](https://basecamp.com/shapeup/3.2-chapter-11#integrate-one-slice) for more info on what your breadboard should be like (and, if you want understand the fat-marker sketch and places affordances drawing better, please see [this page](https://basecamp.com/shapeup/1.3-chapter-04)).

- Make it so that only the user who logged in as CBH can access and stay on this site. The rest will be redirected to home (UGC + Banned Word Dashboard).

🧪 Required Tests
-------------------------------------
_None (but the Code Wizard will review whether or not your code warrants some tests! Review the [Code & Testing Guidelines](https://google.com) for more info)_

⚠️ Careful about:
-------------------

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn

**Comment by Simonwmm** [comment]
i can take this @puma

**Comment by manuelBuitizon** [comment]
I can take this @puma

**Comment by khnatiuk** [comment]
@shop2008 added as HELPER.

**Comment by LeopoldXing** [comment]
https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/123
