### ISSUE TITLE
[5|HR - Setting Page] Feedback

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#87]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 10 points |
| Difficulty rating | ★★☆☆☆| 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
| Fat Marker Sketches | Breadboard |
|:-------|:------:|
|![image](https://github.com/user-attachments/assets/56506723-1c0c-44b1-b39c-8cda98b221a7) | ![image](https://github.com/user-attachments/assets/e1a249eb-8800-4e20-97fc-90483bb60e39)

Feedback button leads to a feedback page, where HR can send texts and import images to give feedback to CBH. 

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, and some integration tests for Supabase and Payload CMS.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS
- Supabase/PostGresQL
- AppFlowy

**Comment by josedsegurav** [comment]
I would like this one @PuMA

**Comment by khnatiuk** [comment]
@josedsegurav you're in!
