### ISSUE TITLE
[3|HR - Setting Page] Reveal Test Account

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#88]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 10 points |
| Difficulty rating | ★★☆☆☆| 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
![image](https://github.com/user-attachments/assets/2aa89242-952b-46ef-bd7b-5ad164255fe7)

When clicking "test account", it shows a dummy test account for HR to log in as an employee.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, and some integration tests for Supabase and Payload CMS.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS
- Supabase/PostGresQL
- AppFlowy

**Comment by NadiiaTysh** [comment]
Can I work on it please? @khnatiuk

**Comment by Eugenia821** [comment]
Kevin, can I join here please? @khnatiuk

**Comment by khnatiuk** [comment]
@Eugenia821 you're in!

**Comment by LeopoldXing** [comment]
https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/205

**Comment by LeopoldXing** [comment]
https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/205
