### ISSUE TITLE
[2|HR - Setting Page] Update Organization information

### ISSUE THREAD

**Issue by hzz4343** [Builder-s-League/BuildersLeague-Edition1#90]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 10 points |
| Difficulty rating | ★★☆☆☆| 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
![image](https://github.com/user-attachments/assets/28473ddd-50b4-42f2-9b9b-e80b4336d3e1)

Build the Setting Page with all of the buttons but don't implement functionality to any button yet.

Implement functionality to the Update Organization button so that HR can change Org name, email, and phone number.

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, and some integration tests for Supabase and Payload CMS.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS
- Supabase/PostGresQL
- AppFlowy

**Comment by samir-otero** [comment]
Hey, I want to take this one @puma

**Comment by josedsegurav** [comment]
I will like this one @Puma

**Comment by khnatiuk** [comment]
@samir-otero @josedsegurav you're on it!

**Comment by al-Sajjadieh** [comment]
Hi, You can use https://ui.shadcn.com/examples/dashboard for better UI !

**Comment by khnatiuk** [comment]
This was merged and so I am closing this issue.

**Comment by khnatiuk** [comment]
This was merged and points assigned so I a closing this issue.
