### ISSUE TITLE
[2|CBH- Setting Page] Set up Setting Page + Email and Phone Numbers Change

### ISSUE THREAD

**Issue by vo-d** [Builder-s-League/BuildersLeague-Edition1#93]
<h2 align="center"> 🍰 Appetite 🍰 </h2>
<div align="center">

| Property | Value |
|:-------|:------:|
| Points | 10 points |
| Difficulty rating | ★★★☆☆| 
| Maximum Assignees | 2 person | 

</div>

🤔 Problem Statement
------------------------------------------
![image](https://github.com/user-attachments/assets/4d745f2d-2f8f-4c13-92b0-6d82d81f81df)

Build the Setting Page with all of the buttons but don't implement functionality to any button yet. 

Implement functionality to the Update Email and Phone so that CBH can update email and phone number

🧪 Required Tests
-------------------------------------
Mainly screenshot tests, and some integration tests for Supabase.
_Review the [Code & Testing Guidelines](https://google.com) for more info._

⚠️ Careful about:
-------------------
No major rabbit holes identified. But always be careful with scope creep!

🤖 Technologies focused on in this feature
---------------------------
- React
- Tailwind
- Shadcn
- NextJS
- Supabase/PostGresQL
- AppFlowy

**Comment by PJ-Bernal** [comment]
I want to work on this one! @puma

**Comment by smtoyedeji** [comment]
I want to be assigned this task @Puma

**Comment by hzz4343** [comment]
@smtoyedeji  sure, here you go

**Comment by Tyson-a** [comment]
I want to be assigned here.

**Comment by hzz4343** [comment]
@Tyson-a  sure, I will assign you

**Comment by khnatiuk** [comment]
@smtoyedeji @Tyson-a how are you still working on this Issue or should we reassign it?

**Comment by khnatiuk** [comment]
MR: [159](https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/159)

**Comment by khnatiuk** [comment]
[Merge Request 159](https://github.com/Builder-s-League/BuildersLeague-Edition1/pull/159)
